# Generated by Django 5.2.10 on 2026-01-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('speed', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
