# Generated by Django 5.2.9 on 2026-01-09 23:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('home', 'Home'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='home', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('speed', models.IntegerField(default=10, help_text='Download speed in Mbps')),
                ('upload_speed', models.IntegerField(blank=True, help_text='Upload speed in Mbps. If not set, assumed symmetric with download.', null=True)),
                ('data_cap', models.IntegerField(blank=True, help_text='Data cap in GB. Leave blank for unlimited.', null=True)),
                ('duration', models.IntegerField(default=30, help_text='Duration in days')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'packages',
                'ordering': ['price'],
            },
        ),
    ]
