# Generated by Django 5.2.10 on 2026-01-09 13:29

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['price'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='data_cap',
            field=models.IntegerField(blank=True, help_text='Data cap in GB. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='plan_type',
            field=models.CharField(choices=[('home', 'Home'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='upload_speed',
            field=models.IntegerField(blank=True, help_text='Upload speed in Mbps. If not set, assumed symmetric with download.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in days'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='package',
            name='speed',
            field=models.IntegerField(default=10, help_text='Download speed in Mbps'),
        ),
        migrations.AlterModelTable(
            name='package',
            table='packages',
        ),
    ]
