"""
Django settings for isp_project project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-d=)2dj!y9+2tdw1w0=iemxd-o1xojas!d&^6*r(5pymehs^1fo"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["testserver", "127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "notifications",
    "packages",
    "payments.apps.PaymentsConfig",
    "reports",
    "subscriptions.apps.SubscriptionsConfig",
    "accounts",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "isp_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "isp_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "isp_db",
        "USER": "admin",
        "PASSWORD": "admin",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# M-Pesa Daraja API Configuration
MPESA_CONFIG = {
    "CONSUMER_KEY": "your_consumer_key_here",  # Replace with actual key
    "CONSUMER_SECRET": "your_consumer_secret_here",  # Replace with actual secret
    "BUSINESS_SHORTCODE": "174379",  # Replace with your shortcode
    "PASSKEY": "your_passkey_here",  # Replace with actual passkey
    "ACCOUNT_REFERENCE": "SpeedNetISP",
    "TRANSACTION_DESC": "Internet Subscription Payment",
    "CALLBACK_URL": "https://yourdomain.com/payments/mpesa/callback/",  # Update with your domain
    "STK_PUSH_URL": "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest",
    "STK_QUERY_URL": "https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query",
    "ACCESS_TOKEN_URL": "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials",
}

# Use sandbox URLs for development, production URLs for live
if not DEBUG:
    MPESA_CONFIG.update(
        {
            "STK_PUSH_URL": "https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest",
            "STK_QUERY_URL": "https://api.safaricom.co.ke/mpesa/stkpushquery/v1/query",
            "ACCESS_TOKEN_URL": "https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials",
        }
    )
